#!/bin/sh
set -eux

# Если это обновление или чистая установка
if [ "$1" = "configure" ]; then
  systemctl daemon-reload >& /dev/null || true
  systemctl enable custom_service.service >& /dev/null || true
  systemctl restart custom_service.service >& /dev/null || true
fi
