#!/bin/sh
set -eux

# Перед удалением пакета отключаем сервис глобально
if [ "$1" = "remove" ]; then
  systemctl stop custom_service.service || true
  systemctl disable custom_service.service || true
  systemctl daemon-reload || true
fi
