#!/bin/sh
set -eux

# Останов пользовательского сервиса невозможно выполнить
# штатной командой systemctl, поэтому используем pkill
pkill \
  --echo \
  --ignore-case \
  --full \
  '^/opt/.*/bin/custom_service.*' || true
systemctl --global disable custom_service.service || true
systemctl daemon-reload || true
